# Habilita o uso do mouse (para clicar em painéis, redimensionar janelas e rolar o histórico)
set -g mouse on
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Configuração recarregada!"
# Muda o prefixo de Ctrl+b para Ctrl+a (muito mais confortável para a mão)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Começa a numeração das janelas e painéis no 1 em vez do 0 (mais fácil de alcançar no teclado)
set -g base-index 1
set -g pane-base-index 1

# Atalhos mais intuitivos para dividir a tela (usa | para vertical e - para horizontal)
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Lista de plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
# Habilita a restauração automática quando o tmux é iniciado
set -g @continuum-restore 'on'

# ~/.tmux.conf

# Options to make tmux more pleasant
set -g mouse on
set -g default-terminal "tmux-256color"


# Load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
# For TPM, instead use `run ~/.tmux/plugins/tmux/catppuccin.tmux`

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# # Or, if using TPM, just run TPM
# set -g @catppuccin_window_left_separator "█"
# set -g @catppuccin_window_right_separator "█ "
# set -g @catppuccin_window_number_position "right"
# set -g @catppuccin_window_middle_separator "  █"

set -g @catppuccin_window_default_fill "number"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#{pane_current_path}"

set -g @catppuccin_status_modules_right "application session date_time"
set -g @catppuccin_status_left_separator  ""
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_right_separator_inverse "yes"
set -g @catppuccin_status_fill "all"
set -g @catppuccin_status_connect_separator "no"
# Or, if using TPM, just run TPM
# Inicializa o TMUX plugin manager (deve ser a ÚLTIMA linha do arquivo)
run '~/.config/tmux/plugins/tpm/tpm'
