unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Configuração recarregada!"
# Muda o prefixo de Ctrl+b para Ctrl+a (muito mais confortável para a mão)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Começa a numeração das janelas e painéis no 1 em vez do 0 (mais fácil de alcançar no teclado)
set -g base-index 1
set -g pane-base-index 1

# Atalhos mais intuitivos para dividir a tela (usa | para vertical e - para horizontal)
set-option -g status-position top
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %
# Lista de plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @plugin 'arcticicestudio/nord-tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

# ~/.tmux.conf

# Options to make tmux more pleasant
set -g mouse on
set -g default-terminal "tmux-256color"
# Propaga cópias do buffer do tmux ao clipboard do terminal via OSC 52.
set -g set-clipboard on

# Inicializa o TMUX plugin manager (deve ser a ÚLTIMA linha do arquivo)
run '~/.config/tmux/plugins/tpm/tpm'
