hl.on("hyprland.start", function()
	hl.exec_cmd("hyprpm reload -n")
	hl.exec_cmd("systemctl --user enable --now hyprpolkitagent")
	hl.exec_cmd("swaync")
	hl.exec_cmd("waybar")
	hl.exec_cmd("waypaper --restore")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("hyprsunset")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("nm-applet --indicator")
	hl.exec_cmd("brave")
	hl.exec_cmd("kitty")
	hl.exec_cmd("elephant")
	hl.exec_cmd("walker --gapplication-service")
end)
