hl.on("hyprland.start", function()
	hl.exec_cmd("hyprpm reload -n")
	hl.exec_cmd("sh -c 'while true; do waybar; sleep 1; done'")
	hl.exec_cmd("mako")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("hyprsunset")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("nm-applet --indicator")
	hl.exec_cmd("brave")
	hl.exec_cmd("brave --app=https://web.whatsapp.com")
	hl.exec_cmd("kitty")
	hl.exec_cmd("elephant")
	hl.exec_cmd("walker --gapplication-service")
end)
