preload = /home/davi/Imagens/Wallpapers/unsorted/a_cartoon_of_a_whale_flying_over_a_road.jpg
wallpaper = eDP-1,/home/davi/Imagens/Wallpapers/unsorted/a_cartoon_of_a_whale_flying_over_a_road.jpg
wallpaper = HDMI-A-1,/home/davi/Imagens/Wallpapers/unsorted/a_cartoon_of_a_whale_flying_over_a_road.jpg
