preload = /home/davi/Imagens/Wallpapers/unsorted/a_cartoon_of_a_whale_flying_over_a_road.jpg
wallpaper {
    monitor = eDP-1
    path = /home/davi/Imagens/Wallpapers/unsorted/a_cartoon_of_a_whale_flying_over_a_road.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/davi/Imagens/Wallpapers/unsorted/a_cartoon_of_a_whale_flying_over_a_road.jpg
    fit_mode = cover
}
